name: emolog
description: "A new Flutter project about mental health care."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  crypto: ^3.0.6
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.4.2
  google_fonts: ^6.3.0
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
